"""A tiny CLI for demonstrating the pipeline without the web stack.

`python -m app.cli demo` scores the spec's acceptance-test example and prints
the result. It touches no database, which makes it the fastest way to see what
the system actually does - and the output in the README is generated by it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from app.db.models import CandidateProfile, JobOpportunity
from app.services.analysis import apply_extraction_to_job
from app.services.extraction import extract
from app.services.missing_info import detect_missing_information
from app.services.response_draft import generate_response_draft
from app.services.scoring import ScoringConfig, ScoringResult, score_opportunity

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "samples"

ACCEPTANCE_EXAMPLE = (
    "Hi Eric, I'm recruiting for a Forward Deployed Engineer supporting national security "
    "customers. The role requires TS/SCI and experience with Python, React, TypeScript, "
    "LLMs, and customer-facing technical delivery. Salary is $190k-$240k plus equity. "
    "Position is onsite in San Francisco with approximately 20% travel. We're looking for "
    "3-5 years full-stack engineering experience."
)


def load_demo_candidate() -> CandidateProfile:
    payload = json.loads((DATA_DIR / "candidate_profile.json").read_text(encoding="utf-8"))
    return CandidateProfile(**payload)


def analyze(text: str, candidate: CandidateProfile) -> tuple[JobOpportunity, ScoringResult]:
    job = apply_extraction_to_job(JobOpportunity(), extract(text, use_llm=False))
    config = ScoringConfig.from_profile(candidate.scoring_config)
    return job, score_opportunity(job, candidate, config)


def _money(value: int | None) -> str:
    return f"${value:,}" if value else "not stated"


def render(job: JobOpportunity, result: ScoringResult, candidate: CandidateProfile) -> str:
    missing = detect_missing_information(job)
    draft = generate_response_draft(
        job, result, missing, candidate_name=candidate.name, polish=False
    )

    lines: list[str] = []
    add = lines.append

    add("=" * 72)
    add(f"  {job.title or 'Untitled opportunity'}" + (f" — {job.company}" if job.company else ""))
    add("=" * 72)
    add("")
    add("EXTRACTED")
    add(f"  Salary        {_money(job.salary_min)} – {_money(job.salary_max)}")
    add(f"  Clearance     {job.security_clearance}")
    add(f"  Polygraph     {job.polygraph_requirement}")
    add(f"  Location      {job.location or 'not stated'} ({job.remote_status})")
    add(f"  Travel        {job.travel if job.travel is not None else 'not stated'}%")
    add(f"  Experience    {job.required_years_experience or 'not stated'} years")
    add(f"  Skills        {', '.join(job.required_skills) or 'none detected'}")
    add(f"  Job family    {job.job_family}")
    add("")
    add("SCORES")
    for label, dimension in (
        ("Current fit", result.fit),
        ("Career capital", result.career_capital),
        ("Proofability", result.proofability),
        ("Compensation", result.compensation),
        ("Lifestyle", result.lifestyle),
        ("Upside", result.upside),
        ("Risk (separate)", result.risk),
    ):
        bar = "█" * int(dimension.score / 5)
        add(f"  {label:<17}{dimension.score:>5.0f}  {bar}")
    add("")
    add(f"  OVERALL          {result.overall:>5.1f}  →  {result.recommended_action.value}")
    add("")
    add("WHY")
    for bullet in result.headline_reasons:
        add(f"  • {bullet}")
    add("")
    add("PROVE-IT")
    add(f"  {result.prove_it['summary']}")
    for item in result.prove_it["learnable"]:
        add(
            f"  → {item['requirement']}: {item['interview_readiness']} — "
            f"{item['how_to_demonstrate']}"
        )
    for item in result.prove_it["hard_gates"]:
        add(f"  ✗ {item['requirement']}: {item['detail']}")
    add("")
    add("MISSING INFORMATION")
    for field in missing[:6]:
        add(f"  {field.priority}. {field.label}")
    add("")
    add("DRAFTED REPLY (for human approval — nothing is sent)")
    for line in draft.body.splitlines():
        add(f"  | {line}")
    add("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="app.cli", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    demo = sub.add_parser("demo", help="Score the acceptance-test example")
    demo.add_argument("--file", type=Path, help="Score a file instead of the built-in example")
    demo.add_argument("--json", action="store_true", help="Emit JSON rather than a report")

    args = parser.parse_args(argv)

    text = args.file.read_text(encoding="utf-8") if args.file else ACCEPTANCE_EXAMPLE
    candidate = load_demo_candidate()
    job, result = analyze(text, candidate)

    if args.json:
        print(
            json.dumps(
                {
                    "opportunity": {
                        "title": job.title,
                        "company": job.company,
                        "salary_min": job.salary_min,
                        "salary_max": job.salary_max,
                        "security_clearance": job.security_clearance,
                        "polygraph_requirement": job.polygraph_requirement,
                        "required_skills": job.required_skills,
                        "job_family": job.job_family,
                    },
                    "scores": {
                        name: round(dimension.score, 1)
                        for name, dimension in result.dimensions().items()
                    },
                    "overall": result.overall,
                    "recommended_action": result.recommended_action.value,
                    "explanation": result.explanation(),
                },
                indent=2,
            )
        )
    else:
        print(render(job, result, candidate))
    return 0


if __name__ == "__main__":  # pragma: no cover - operational entrypoint
    sys.exit(main())
